apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prod-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: prod-serviceaccount
  namespace: prod
roleRef:
  kind: ClusterRole
  name: prod
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: master-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: prod-serviceaccount
  namespace: prod
roleRef:
  kind: ClusterRole
  name: master
  apiGroup: rbac.authorization.k8s.io
