# cert-manager Helm Values
installCRDs: true

serviceAccount:
  create: true  # ServiceAccount 생성
  name: cert-manager

# 리소스 제한 (비용 최적화)
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

webhook:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

cainjector:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Prometheus 메트릭
prometheus:
  enabled: true
  servicemonitor:
    enabled: false  # ServiceMonitor 설치 안 함
