apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v2.7.0
    helm.sh/chart: aws-load-balancer-controller-1.7.0
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::014125597282:role/eksctl-gary-cluster-addon-iamserviceaccount-k-Role1-DgvJB0W7r2AT
automountServiceAccountToken: true
