# 네임스페이스 관리 애플리케이션
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  labels:
    app.kubernetes.io/name: namespaces
spec:
  project: default
  source:
    repoURL: https://github.com/gary/gary-cluster.git
    targetRevision: HEAD
    path: applications/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# 스모크 테스트 애플리케이션
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smoke-test
  namespace: argocd
  labels:
    app.kubernetes.io/name: smoke-test
spec:
  project: default
  source:
    repoURL: https://github.com/gary/gary-cluster.git
    targetRevision: HEAD
    path: applications/smoke-test
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# Gary Apps 애플리케이션들
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gary-apps-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: gary-apps-dev
spec:
  project: default
  source:
    repoURL: https://github.com/gary/gary-cluster.git
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gary-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
