# 네임스페이스 관리 애플리케이션 (단일 네임스페이스 gary-app)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  labels:
    app.kubernetes.io/name: namespaces
spec:
  project: default
  source:
    repoURL: https://github.com/gary/gary-cluster.git  # GitHub 사용자명 설정
    targetRevision: HEAD
    path: applications/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: gary-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

# 불필요한 dev/prod/gary-apps 애플리케이션 정의 제거
