apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-backend
spec:
  selector:
    matchLabels:
      app: ims-backend
      tier: backend
  revisionHistoryLimit: 3
  replicas: 1
  template:
    metadata:
      labels:
        app: ims-backend
        tier: backend
        env: dev
        version: v1
    spec:
      containers:
      - name: ims-backend
        # Local Docker Desktop에서 Registry를 사용하는 경우 
        # host.docker.internal:<registry port>로 이미지에 접근해야한다.
        image: host.docker.internal:10000/ims-backend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: APP_ENV
          value: dev
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-token-secret
              key: GIT_TOKEN
        resources:
          requests:
            memory: 300M
            cpu: 8m
          limits:
            memory: 500M
            cpu: 10m
      nodeSelector:
        # 로컬 쿠버네티스에서 hostname을 적용하는 경우 Name Tag가 다름
        # 실제 EKS 등의 서비스를 통해서 쿠버네티스를 적용하는 경우 kubernetes.io/hostname가 아닌 hostname으로 사용
        kubernetes.io/hostname: docker-desktop
