apiVersion: v1
kind: Service
metadata:
  name: ims-backend-service
spec:
  type: NodePort
  selector:
    app: ims-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: http
    nodePort: 31000
