apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    # Service의 Selector와 일치해야한다.
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      # Service의 Selector가 참조하는 부분으로 Service의 Label과 일치해야한다.
      app: nginx-app
  template:
    metadata:
      # Pod에 적용되는 라벨, Service의 Label과 일치해야한다.
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.7
        # Pod의 Input Port 정의
        ports:
        - name: http
          containerPort: 80
        # Pod의 Resource를 정의
        resources:
          limits:
            memory: 256Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "1"
