apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      role: arn:aws:iam::014125597282:role/eso-household-ledger
      auth:
        jwt:
          serviceAccountRef:
            name: household-ledger-sa
            namespace: gary-app

