# gitops/applications/household-ledger/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: household-ledger
  namespace: gary-app
  labels:
    app: household-ledger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: household-ledger
  template:
    metadata:
      labels:
        app: household-ledger
    spec:
      containers:
        - name: household-ledger
          image: 014125597282.dkr.ecr.ap-northeast-2.amazonaws.com/household-ledger:latest # Image will be updated by ArgoCD Image Updater
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: household-ledger-secrets
                  key: database-url
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: household-ledger-secrets
                  key: nextauth-secret
            - name: NEXTAUTH_URL
              value: "https://household-ledger.garyzone.pro"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: household-ledger-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: household-ledger-secrets
                  key: google-client-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
