apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gary-ingress
  namespace: default
spec:
  rules:
  - host: gary.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gary-service
            port:
              number: 80
